### ISSUE TITLE
죄송하지만, 언어 순화하시는걸 부탁드리며, 부계정을 쓰시는 이유를 묻고싶습니다.

### ISSUE THREAD

**Issue by xuserwhat** [SoManyIdiotsInKKuTuIssues/Introduce#1]
죄송하지만, 볼때마다 사람 불쾌하게 만드네요.
이의 제기하시려면 조금이나마 언어 순화좀 하시지, 제 3자 입장에서도 상당히 반달수준으로 불쾌합니다.
공익성을 고려하시면 공익성 생각하시면서 답변 쓰세요 보는사람마다 불쾌하게 하시지 말고.
그리고 왜 부계정을 쓰시는지 묻고싶네요.
답변해주시면 감사하겠습니다.

**Comment by KORraimi** [comment]
@xuserwhat 네? 부계에요?

**Comment by KORraimi** [comment]
그리고 왜 이런 일은 하는거죠. 굳이 자신의 시간을 낭비하면서까지 이렇고 싶지는 않을껍니다. 그리고 [[이거]] 뭡니까? 저 나무위키 합니다 ^^ 라고 표현하시나요? 정말로 웃기십니다

**Comment by xuserwhat** [comment]
SoManyIdiotsKKuTuIssues 님의 본계정이 따로 있으시다고 README 에 적어놓으셨습니다.

**Comment by KORraimi** [comment]
ㅇㅎ
.

**Comment by KORraimi** [comment]
저도 화났는게 약간 상대방을 갉아 내리는듯한 언어와 가독하기 힘든 급식체, 입에 담기도 힘든 말을 섞어 쓰셔셔 보기가 약간 그랬습니다. 생각해보세요. 누군가 자신을 욕하면 가만히 있겠습니까? 그건 찐따나 그런짓 하죠.

**Comment by KORraimi** [comment]
그리고 그 표현 그대로 쓰시면 명예훼손죄 성립되서 저가 얼마든지 고소도 가능하기 때문이죠.
1. 공연성: 이는 끄투 레포지토리에 올라가기 때문에 누구나 볼수있기 때문에 성립.
2. 특정성: 본인 이슈에 달았기 때문에 본인을 저격하여 특정성 성립
그래서 고소 가능합니다.

**Comment by KORraimi** [comment]
여기서도 욕 하면 고소절차 밟겠습니다

**Comment by xuserwhat** [comment]
죄송하지만 고소는 지속적으로 피해당하신게 입증이 되셔야 되실겁니다. 여기에서는 공익적인 이의만 말씀해주시면 감사하겠습니다.

**Comment by xuserwhat** [comment]
익명성을 이용해서 특정 분께 비방을 하실 필요가 있을까요?

**Comment by SoManyIdiotsInKKuTuIssues** [comment]
@KORraimi 븅신 지 프로필사진부터 꺼라위키인데 사돈남말하네

@xuserwhat 죄송하지만 본 계정 생성 목적부터가 그런거라서 그만둘 생각은 없습니다 ㅎ 즐
