### ISSUE TITLE
왜 숨 쉬니? 왜 태어났니?

### ISSUE THREAD

**Issue by kjbkjb1122** [SoManyIdiotsInKKuTuIssues/Introduce#2]
**깃허브는 저격하는 곳이 아니라 문제 해결소다. 븅신새꺄?
저격을 할 꺼면 뭘 알고해
저격의 저 뜻도 모르는 새끼가 니가 남긴 이슈 쳐보니까 시발 몸이 16도 30등분으로 잘린 새끼가 뭘 안다고 헛소리를 다 하네?  그런 너를 보니까 진짜 뇌가 텅 비웠는지 모르겠다 ㅉㅉ 그리고 부계정이 자랑이냐? ㅋㅋㅋ 나중에 이 이슈보고 분명 존나 쪽팔린거 인정해서 자살 각이다. 이 최저질 초딩 조옺 병신 염병새끼때문에 바른 초등학생이 욕먹는 거다. 이거나 처보고 질질 울거라~~ ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ**

**Comment by SoManyIdiotsInKKuTuIssues** [comment]
지가 싸지른 수준낮은 드립 보고 내가 질질 짤거라고 생각하누 ㅋㅋㅋㅋㅋ

집 가서 자라 아그야
